        // CONFIGURACIÓN LOCAL
        const MAL_USERNAME = "Andreapova";

        const MIS_SERIES_VISTAS = [
            { titulo: "The Boys", col: 0, fila: 0, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Amadeus", col: 1, fila: 0, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Game of Thrones", col: 2, fila: 0, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "Star Wars: The Bad Batch", col: 0, fila: 1, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Spartacus", col: 1, fila: 1, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Mussolini: Son of the Century", col: 2, fila: 1, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "Vikings", col: 0, fila: 2, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Spartacus: House of Ashur", col: 1, fila: 2, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "True Detective", col: 2, fila: 2, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "Chespirito", col: 0, fila: 3, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Squid Game", col: 1, fila: 3, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Star Wars: Andor", col: 2, fila: 3, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "Gundam: Requiem for Vengeance", col: 0, fila: 4, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Lawmen: Bass Reeves", col: 1, fila: 4, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Loki", col: 2, fila: 4, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "Stranger Things", col: 0, fila: 5, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "The Mandalorian", col: 1, fila: 5, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Servant", col: 2, fila: 5, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "The Terror", col: 0, fila: 6, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "The Watcher", col: 1, fila: 6, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Bárbaros", col: 2, fila: 6, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "You", col: 0, fila: 7, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Hitler's Circle of Evil", col: 1, fila: 7, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "All or Nothing: All Blacks", col: 2, fila: 7, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "Rome", col: 0, fila: 8, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "The Night Manager", col: 1, fila: 8, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Ozark", col: 2, fila: 8, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "The Walking Dead", col: 0, fila: 9, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Blackbird", col: 1, fila: 9, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Savage River", col: 2, fila: 9, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "Warrior", col: 0, fila: 10, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Serie Extra 1", col: 1, fila: 10, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Serie Extra 2", col: 2, fila: 10, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" },
            { titulo: "Serie Extra 3", col: 0, fila: 11, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Serie Extra 4", col: 1, fila: 11, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }, { titulo: "Próximamente...", col: 2, fila: 11, imagen: "https://images4.imagebam.com/4e/05/51/ME1EH3BA_o.jpg" }
        ];

        const MIS_ANIMES_VISTOS = [
          { titulo: "5-toubun no Hanayome", imagen: "https://cdn.myanimelist.net/images/anime/1075/122031.jpg" },
          { titulo: "5-toubun no Hanayome ∬", imagen: "https://cdn.myanimelist.net/images/anime/1775/109514.webp" },
          { titulo: "86", imagen: "https://cdn.myanimelist.net/images/anime/1987/117507.webp" },
          { titulo: "86 Part 2", imagen: "https://cdn.myanimelist.net/images/anime/1321/117508.webp" },
          { titulo: "86 Special Edition: Senya ni Akaku Hinageshi no Saku", imagen: "https://cdn.myanimelist.net/images/anime/1971/115976.webp" },
          { titulo: "Akebi-chan no Sailor-fuku", imagen: "https://cdn.myanimelist.net/images/anime/1820/120520.webp" },
          { titulo: "Akikan!", imagen: "https://cdn.myanimelist.net/images/anime/5/47093.webp" },
          { titulo: "Akira", imagen: "https://cdn.myanimelist.net/images/anime/1408/114012.webp" },
          { titulo: "Akudama Drive", imagen: "https://cdn.myanimelist.net/images/anime/1468/109172.webp" },
          { titulo: "Angel Cop", imagen: "https://cdn.myanimelist.net/images/anime/1377/110296.webp" },
          { titulo: "Another", imagen: "https://cdn.myanimelist.net/images/anime/4/75509.webp" },
          { titulo: "Asura", imagen: "https://cdn.myanimelist.net/images/anime/7/44289.webp" },
          { titulo: "Babylon", imagen: "https://cdn.myanimelist.net/images/anime/1942/102707.webp" },
          { titulo: "Biohazard: Infinite Darkness", imagen: "https://cdn.myanimelist.net/images/anime/1691/152501.webp" },
          { titulo: "Bokutachi wa Benkyou ga Dekinai", imagen: "https://cdn.myanimelist.net/images/anime/1602/100510.webp" },
          { titulo: "Bokutachi wa Benkyou ga Dekinai: Nagisa ni Usemono Arite Senjin wa Enzen to [X] Suru", imagen: "https://cdn.myanimelist.net/images/anime/1530/102782.webp" },
          { titulo: "Boogiepop wa Warawanai (2019)", imagen: "https://cdn.myanimelist.net/images/anime/1135/95454.webp" },
          { titulo: "Burn the Witch", imagen: "https://cdn.myanimelist.net/images/anime/1993/108967.webp" },
          { titulo: "Candy Boy: Nonchalant Talk of the Certain Twin Sisters in Daily Life", imagen: "https://cdn.myanimelist.net/images/anime/10/13663.webp" },
          { titulo: "Chainsaw Man", imagen: "https://cdn.myanimelist.net/images/anime/1806/126216.webp" },
          { titulo: "Citrus", imagen: "https://cdn.myanimelist.net/images/anime/11/89985.webp" },
          { titulo: "Cyberpunk: Edgerunners", imagen: "https://cdn.myanimelist.net/images/anime/1818/126435.webp" },
          { titulo: "Dagashi Kashi", imagen: "https://cdn.myanimelist.net/images/anime/1538/95686.webp" },
          { titulo: "Dagashi Kashi 2", imagen: "https://cdn.myanimelist.net/images/anime/1649/90141.webp" },
          { titulo: "Dumbbell Nan Kilo Moteru?", imagen: "https://cdn.myanimelist.net/images/anime/1385/101060.webp" },
          { titulo: "Fangkai Nage Nuwu", imagen: "https://cdn.myanimelist.net/images/anime/1381/153536.webp" },
          { titulo: "Fumetsu no Anata e", imagen: "https://cdn.myanimelist.net/images/anime/1880/118484.webp" },
          { titulo: "Fumetsu no Anata e: Fushi no Tabiji", imagen: "https://cdn.myanimelist.net/images/anime/1130/116106.webp" },
          { titulo: "Gamers!", imagen: "https://cdn.myanimelist.net/images/anime/4/86828.webp" },
          { titulo: "Girly Air Force", imagen: "https://cdn.myanimelist.net/images/anime/1046/97025.webp" },
          { titulo: "Gleipnir", imagen: "https://cdn.myanimelist.net/images/anime/1808/111697.webp" },
          { titulo: "Goblin Slayer: Goblin's Crown", imagen: "https://cdn.myanimelist.net/images/anime/1699/110724.webp" },
          { titulo: "Godzilla: S.P", imagen: "https://cdn.myanimelist.net/images/anime/1447/114837.webp" },
          { titulo: "Grand Blue", imagen: "https://cdn.myanimelist.net/images/anime/1302/94882.webp" },
          { titulo: "Harukana Receive", imagen: "https://cdn.myanimelist.net/images/anime/1924/95212.webp" },
          { titulo: "Hataraku Saibou Black", imagen: "https://cdn.myanimelist.net/images/anime/1837/110799.webp" },
          { titulo: "Hibike! Euphonium Movie 1: Kitauji Koukou Suisougaku-bu e Youkoso", imagen: "https://cdn.myanimelist.net/images/anime/8/81156.webp" },
          { titulo: "Hibike! Euphonium Movie 2: Todoketai Melody", imagen: "https://cdn.myanimelist.net/images/anime/5/88024.webp" },
          { titulo: "Hibike! Euphonium Movie 3: Chikai no Finale", imagen: "https://cdn.myanimelist.net/images/anime/1141/102223.webp" },
          { titulo: "Hige wo Soru. Soshite Joshikousei wo Hirou.", imagen: "https://cdn.myanimelist.net/images/anime/1146/113477.webp" },
          { titulo: "Hirune Hime: Shiranai Watashi no Monogatari", imagen: "https://cdn.myanimelist.net/images/anime/7/84071.webp" },
          { titulo: "Ijiranaide, Nagatoro-san", imagen: "https://cdn.myanimelist.net/images/anime/1900/110097.webp" },
          { titulo: "Ikkitousen", imagen: "https://cdn.myanimelist.net/images/anime/1097/133583.webp" },
          { titulo: "Ikkitousen: Dragon Destiny", imagen: "https://cdn.myanimelist.net/images/anime/6/85202.webp" },
          { titulo: "Ikkitousen: Dragon Destiny Specials", imagen: "https://cdn.myanimelist.net/images/anime/1636/138210.webp" },
          { titulo: "Ikkitousen: Extravaganza Epoch", imagen: "https://cdn.myanimelist.net/images/anime/1413/133384.webp" },
          { titulo: "Ikkitousen: Great Guardians", imagen: "https://cdn.myanimelist.net/images/anime/2/22922.webp" },
          { titulo: "Ikkitousen: Great Guardians Specials", imagen: "https://cdn.myanimelist.net/images/anime/1639/138207.webp" },
          { titulo: "Ikkitousen: Shuugaku Toushi Keppuuroku", imagen: "https://cdn.myanimelist.net/images/anime/1452/138211.webp" },
          { titulo: "Ikkitousen: Western Wolves", imagen: "https://cdn.myanimelist.net/images/anime/1355/98146.webp" },
          { titulo: "Ikkitousen: Xtreme Xecutor", imagen: "https://cdn.myanimelist.net/images/anime/2/18209.webp" },
          { titulo: "Ikkitousen: Xtreme Xecutor Specials", imagen: "https://cdn.myanimelist.net/images/anime/10/22814.webp" },
          { titulo: "Interstella5555: The 5tory of The 5ecret 5tar 5ystem", imagen: "https://cdn.myanimelist.net/images/anime/1618/146985.webp" },
          { titulo: "Isekai Meikyuu de Harem wo", imagen: "https://cdn.myanimelist.net/images/anime/1490/126919.webp" }, 
          { titulo: "Iya na Kao sare nagara Opantsu Misete Moraitai", imagen: "https://cdn.myanimelist.net/images/anime/1887/95009l.jpg" },
          { titulo: "Jahy-sama wa Kujikenai!", imagen: "https://cdn.myanimelist.net/images/anime/1154/115599.webp" },
          { titulo: "Jin-Rou", imagen: "https://cdn.myanimelist.net/images/anime/1323/103343.webp" },
          { titulo: "JoJo no Kimyou na Bouken Part 5: Ougon no Kaze Recaps", imagen: "https://cdn.myanimelist.net/images/anime/1398/122100.webp" },
          { titulo: "JoJo no Kimyou na Bouken Part 6: Stone Ocean", imagen: "https://cdn.myanimelist.net/images/anime/1896/119844.webp" },
          { titulo: "Joshikausei", imagen: "https://cdn.myanimelist.net/images/anime/1748/111393.webp" },
          { titulo: "Jujutsu Kaisen", imagen: "https://cdn.myanimelist.net/images/anime/1171/109222.webp" },
          { titulo: "Kaizoku Oujo", imagen: "https://cdn.myanimelist.net/images/anime/1607/117951.webp" },
          { titulo: "Kanojo mo Kanojo", imagen: "https://cdn.myanimelist.net/images/anime/1713/117119.webp" },
          { titulo: "Kanojo, Okarishimasu", imagen: "https://cdn.myanimelist.net/images/anime/1902/128382.webp" },
          { titulo: "Kara no Kyoukai Movie 1: Fukan Fuukei", imagen: "https://cdn.myanimelist.net/images/anime/12/21741.webp" },
          { titulo: "Keijo!!!!!!!!", imagen: "https://cdn.myanimelist.net/images/anime/10/81906.webp" },
          { titulo: "Kidou Senshi Gundam 0080: Pocket no Naka no Sensou", imagen: "https://cdn.myanimelist.net/images/anime/1839/92857.webp" },
          { titulo: "Kidou Senshi Gundam: Cucuruz Doan no Shima", imagen: "https://cdn.myanimelist.net/images/anime/1629/124154.webp" },
          { titulo: "Kidou Senshi Gundam: Dai 08 MS Shoutai", imagen: "https://cdn.myanimelist.net/images/anime/9/75618.webp" },
          { titulo: "Kidou Senshi Gundam: Dai 08 MS Shoutai - Miller's Report", imagen: "https://cdn.myanimelist.net/images/anime/1132/100198.webp" },
          { titulo: "Kidou Senshi Gundam: Fukushuu no Requiem", imagen: "https://cdn.myanimelist.net/images/anime/1928/144472.webp" },
          { titulo: "Kidou Senshi Gundam: Senkou no Hathaway", imagen: "https://cdn.myanimelist.net/images/anime/1195/115685.webp" },
          { titulo: "Kimi no Na wa.", imagen: "https://cdn.myanimelist.net/images/anime/5/87048.webp" },
          { titulo: "Kimi no Suizou wo Tabetai", imagen: "https://cdn.myanimelist.net/images/anime/1768/93291.webp" },
          { titulo: "Koi to Yobu ni wa Kimochi Warui", imagen: "https://cdn.myanimelist.net/images/anime/1519/110527.webp" },
          { titulo: "Koi wa Ameagari no You ni", imagen: "https://cdn.myanimelist.net/images/anime/1271/90136.webp" },
          { titulo: "Koi wa Sekai Seifuku no Ato de", imagen: "https://cdn.myanimelist.net/images/anime/1347/120593.webp" },
          { titulo: "Komi-san wa, Comyushou desu.", imagen: "https://cdn.myanimelist.net/images/anime/1899/117237.webp" },
          { titulo: "Koukaku Kidoutai 2.0", imagen: "https://cdn.myanimelist.net/images/anime/1797/152914.webp" },
          { titulo: "Koukaku Kidoutai: SAC_2045", imagen: "https://cdn.myanimelist.net/images/anime/1213/106702.webp" },
          { titulo: "Kouya no Kotobuki Hikoutai", imagen: "https://cdn.myanimelist.net/images/anime/1252/96179.webp" },
          { titulo: "Kyuukyoku Shinka shita Full Dive RPG ga Genjitsu yori mo Kusoge Dattara", imagen: "https://cdn.myanimelist.net/images/anime/1357/113277.webp" }, 
          { titulo: "Mardock Scramble: The Second Combustion", imagen: "https://cdn.myanimelist.net/images/anime/1791/112725l.jpg" },
          { titulo: "Megalo Box", imagen: "https://cdn.myanimelist.net/images/anime/1958/93533.webp" },
          { titulo: "Mieruko-chan", imagen: "https://cdn.myanimelist.net/images/anime/1277/117155.webp" },
          { titulo: "Miru Tights", imagen: "https://cdn.myanimelist.net/images/anime/1122/103222.webp" },
          { titulo: "Musaigen no Phantom World", imagen: "https://cdn.myanimelist.net/images/anime/4/78339.webp" },
          { titulo: "Musaigen no Phantom World: Limitless Phantom World", imagen: "https://cdn.myanimelist.net/images/anime/9/79855.webp" },
          { titulo: "Nakitai Watashi wa Neko wo Kaburu", imagen: "https://cdn.myanimelist.net/images/anime/1045/106389.webp" },
          { titulo: "Nande Koko ni Sensei ga!?", imagen: "https://cdn.myanimelist.net/images/anime/1765/99673.webp" },
          { titulo: "Nande Koko ni Sensei ga!? Nande Koko ni Sensei-tachi ga!?", imagen: "https://cdn.myanimelist.net/images/anime/1702/102607.webp" },
          { titulo: "Nisekoi", imagen: "https://cdn.myanimelist.net/images/anime/13/75587.webp" },
          { titulo: "No Guns Life", imagen: "https://cdn.myanimelist.net/images/anime/1531/102113.webp" },
          { titulo: "No Guns Life 2nd Season", imagen: "https://cdn.myanimelist.net/images/anime/1477/106613.webp" },
          { titulo: "Nobunaga-sensei no Osanazuma", imagen: "https://cdn.myanimelist.net/images/anime/1524/97286.webp" },
          { titulo: "Nomad: Megalo Box 2", imagen: "https://cdn.myanimelist.net/images/anime/1190/113352.webp" },
          { titulo: "Ore wo Suki nano wa Omae dake ka yo", imagen: "https://cdn.myanimelist.net/images/anime/1348/102797.webp" },
          { titulo: "Ouritsu Uchuugun: Honneamise no Tsubasa", imagen: "https://cdn.myanimelist.net/images/anime/1811/112663.webp" },
          { titulo: "Perfect Blue", imagen: "https://cdn.myanimelist.net/images/anime/1254/134212.webp" },
          { titulo: "Prison School", imagen: "https://cdn.myanimelist.net/images/anime/1286/112161.webp" },
          { titulo: "Psycho-Pass 3", imagen: "https://cdn.myanimelist.net/images/anime/1406/104344.webp" },
          { titulo: "Psycho-Pass: Sinners of the System Case.1 - Tsumi to Batsu", imagen: "https://cdn.myanimelist.net/images/anime/1623/96878.webp" },
          { titulo: "Psycho-Pass: Sinners of the System Case.2 - First Guardian", imagen: "https://cdn.myanimelist.net/images/anime/1357/96879.webp" },
          { titulo: "Shingeki no Kyojin", imagen: "https://cdn.myanimelist.net/images/anime/10/47347.webp" },
          { titulo: "Shingeki no Kyojin Season 3 Part 2", imagen: "https://cdn.myanimelist.net/images/anime/1517/100633.webp" },
          { titulo: "Shingeki no Kyojin: Chronicle", imagen: "https://cdn.myanimelist.net/images/anime/1786/110717.webp" },
          { titulo: "Shingeki no Kyojin: The Final Season", imagen: "https://cdn.myanimelist.net/images/anime/1000/110531.webp" },
          { titulo: "Shingeki no Kyojin: The Final Season Part 2", imagen: "https://cdn.myanimelist.net/images/anime/1948/120625.webp" },
          { titulo: "Shisha no Teikoku", imagen: "https://cdn.myanimelist.net/images/anime/4/75468.webp" },
          { titulo: "Shokugeki no Souma: Gou no Sara", imagen: "https://cdn.myanimelist.net/images/anime/1756/108000.webp" },
          { titulo: "Shokugeki no Souma: Shin no Sara", imagen: "https://cdn.myanimelist.net/images/anime/1072/110175.webp" },
          { titulo: "Shuumatsu no Harem", imagen: "https://cdn.myanimelist.net/images/anime/1491/117296.webp" },
          { titulo: "Sirius", imagen: "https://cdn.myanimelist.net/images/anime/1456/94897.webp" },
          { titulo: "Sono Bisque Doll wa Koi wo Suru", imagen: "https://cdn.myanimelist.net/images/anime/1179/119897.webp" },
          { titulo: "Sounan desu ka?", imagen: "https://cdn.myanimelist.net/images/anime/1741/102237.webp" },
          { titulo: "Star Wars: Visions", imagen: "https://cdn.myanimelist.net/images/anime/1958/117686.webp" },
          { titulo: "Steamboy", imagen: "https://cdn.myanimelist.net/images/anime/11/21278.webp" },
          { titulo: "Stranger: Mukou Hadan", imagen: "https://cdn.myanimelist.net/images/anime/9/87066.webp" },
          { titulo: "Super Cub", imagen: "https://cdn.myanimelist.net/images/anime/1776/111172.webp" },
          { titulo: "Tayutama: Kiss on My Deity", imagen: "https://cdn.myanimelist.net/images/anime/1094/153283.webp" },
          { titulo: "Tenjou Tenge", imagen: "https://cdn.myanimelist.net/images/anime/1507/101835.webp" },
          { titulo: "Tenki no Ko", imagen: "https://cdn.myanimelist.net/images/anime/1880/101146.webp" },
          { titulo: "Tenkuu Shinpan", imagen: "https://cdn.myanimelist.net/images/anime/1547/117947.webp" },
          { titulo: "Tetsuwan Birdy Decode:02", imagen: "https://cdn.myanimelist.net/images/anime/10/53907.webp" },
          { titulo: "The Sky Crawlers", imagen: "https://cdn.myanimelist.net/images/anime/8/8212.webp" },
          { titulo: "Tokyo Revengers", imagen: "https://cdn.myanimelist.net/images/anime/1839/122012.webp" },
          { titulo: "Uchuu Senkan Yamato 2202: Ai no Senshi-tachi", imagen: "https://cdn.myanimelist.net/images/anime/7/84463.webp" },
          { titulo: "Ultraman", imagen: "https://cdn.myanimelist.net/images/anime/1774/116478.webp" },
          { titulo: "Uzaki-chan wa Asobitai!", imagen: "https://cdn.myanimelist.net/images/anime/1540/108292.webp" },
          { titulo: "Vinland Saga", imagen: "https://cdn.myanimelist.net/images/anime/1500/103005.webp" },
          { titulo: "Violet Evergarden Movie", imagen: "https://cdn.myanimelist.net/images/anime/1825/110716.webp" },
          { titulo: "Yakusoku no Neverland", imagen: "https://cdn.myanimelist.net/images/anime/1830/118780.webp" },
          { titulo: "Yakusoku no Neverland 2nd Season", imagen: "https://cdn.myanimelist.net/images/anime/1815/110626.webp" },
          { titulo: "Zankyou no Terror", imagen: "https://cdn.myanimelist.net/images/anime/1417/117422.webp" },
          { titulo: "Zombieland Saga", imagen: "https://cdn.myanimelist.net/images/anime/1084/128208.webp" },
          { titulo: "Zombieland Saga Revenge", imagen: "https://cdn.myanimelist.net/images/anime/1118/115156.webp" }
        ];